package fmod;

@:native('FMOD_DSP_TYPE')
enum abstract DSPType(Int)
{
    // @:native('FMOD_DSP_TYPE_UNKNOWN')
    var Unknown;
    // @:native('FMOD_DSP_TYPE_MIXER')
    var Mixer;
    // @:native('FMOD_DSP_TYPE_OSCILLATOR')
    var Oscillator;
    // @:native('FMOD_DSP_TYPE_LOWPASS')
    var Lowpass;
    // @:native('FMOD_DSP_TYPE_ITLOWPASS')
    var ITLowpass;
    // @:native('FMOD_DSP_TYPE_HIGHPASS')
    var Highpass;
    // @:native('FMOD_DSP_TYPE_ECHO')
    var Echo;
    // @:native('FMOD_DSP_TYPE_FADER')
    var Fader;
    // @:native('FMOD_DSP_TYPE_FLANGE')
    var Flange;
    // @:native('FMOD_DSP_TYPE_DISTORTION')
    var Distortion;
    // @:native('FMOD_DSP_TYPE_NORMALIZE')
    var Normalize;
    // @:native('FMOD_DSP_TYPE_LIMITER')
    var Limiter;
    // @:native('FMOD_DSP_TYPE_PARAMEQ')
    var ParamEQ;
    // @:native('FMOD_DSP_TYPE_PITCHSHIFT')
    var PitchShift;
    // @:native('FMOD_DSP_TYPE_CHORUS')
    var Chorus;
    // @:native('FMOD_DSP_TYPE_VSTPLUGIN')
    var VSTPlugin;
    // @:native('FMOD_DSP_TYPE_WINAMPPLUGIN')
    var WinampPlugin;
    // @:native('FMOD_DSP_TYPE_ITECHO')
    var ITEcho;
    // @:native('FMOD_DSP_TYPE_COMPRESSOR')
    var Compressor;
    // @:native('FMOD_DSP_TYPE_SFXREVERB')
    var SFXReverb;
    // @:native('FMOD_DSP_TYPE_LOWPASS_SIMPLE')
    var LowpassSimple;
    // @:native('FMOD_DSP_TYPE_DELAY')
    var Delay;
    // @:native('FMOD_DSP_TYPE_TREMOLO')
    var Tremolo;
    // @:native('FMOD_DSP_TYPE_LADSPAPLUGIN')
    var LADSPAPlugin;
    // @:native('FMOD_DSP_TYPE_SEND')
    var Send;
    // @:native('FMOD_DSP_TYPE_RETURN')
    var Return;
    // @:native('FMOD_DSP_TYPE_HIGHPASS_SIMPLE')
    var HighpassSimple;
    // @:native('FMOD_DSP_TYPE_PAN')
    var Pan;
    // @:native('FMOD_DSP_TYPE_THREE_EQ')
    var ThreeEQ;
    // @:native('FMOD_DSP_TYPE_FFT')
    var FFT;
    // @:native('FMOD_DSP_TYPE_LOUDNESS_METER')
    var LoudnessMeter;
    // @:native('FMOD_DSP_TYPE_ENVELOPEFOLLOWER')
    var EnvelopeFollower;
    // @:native('FMOD_DSP_TYPE_CONVOLUTIONREVERB')
    var ConvolutionReverb;
    // @:native('FMOD_DSP_TYPE_CHANNELMIX')
    var ChannelMix;
    // @:native('FMOD_DSP_TYPE_TRANSCEIVER')
    var Transceiver;
    // @:native('FMOD_DSP_TYPE_OBJECTPAN')
    var ObjectPan;
    // @:native('FMOD_DSP_TYPE_MULTIBAND_EQ')
    var MultibandEQ;
    // @:native('FMOD_DSP_TYPE_MAX')
    var Max;
}